#![forbid(unsafe_code)]

pub mod agent_detect;
pub mod agent_notify;
pub mod agent_setup;
pub mod agent_status;
pub mod cli;
pub mod client;
pub mod config;
pub mod daemon;
pub mod failover;
pub mod fleet;
pub mod hosted_rendezvous;
pub mod kitty_keyboard;
pub mod layout;
pub mod lease;
pub mod ledger;
pub mod local_ipc;
pub mod machine_id;
pub mod node;
pub mod pairing;
mod perf;
pub mod protocol;
pub mod pty_host;
pub mod screen;
pub mod session;
pub mod session_store;
pub mod ticket;
pub mod transport;
pub mod tui;
pub mod update_check;
